# Generated by Django 5.0.6 on 2024-06-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todotask_id_todotask_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='isCompleted',
            field=models.CharField(max_length=20),
        ),
    ]
