# Generated by Django 5.0.6 on 2024-06-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todotask_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='isCompleted',
        ),
    ]
