# Generated by Django 5.0.6 on 2024-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_todotask_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='completedstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
